[Greeter]
# Background image
background=$backgrounds_dir/desktop-wallpaper.png
# Optional: Enable user background selection
draw-user-backgrounds=false
draw-grid=true
# Theme settings
theme-name=Arc-dark
icon-theme-name=Qogir
cursor-theme-name=Qogir
cursor-theme-size=16
# Other Settings
show-a11y=false
show-power=false
background-color=#000000
show-clock=true
clock-format=%H:%M
